### ISSUE TITLE
CORS error on fetching

### ISSUE THREAD

**Issue by dragosdydy** [frandiox/medium-json-feed#1]
Hello,
I am trying to use this package in my React app but I get the CORS error.

`Failed to load https://medium.com/@username?format=json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localdomain.test' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

My code for the request is:

```
mediumJSONFeed(username)
        .then(response => {
            console.error("Success: ", response);
        })
        .catch(err => {
            console.error("Failure: ", err);
 });
```
Any suggestions ?

**Comment by frandiox** [comment]
@dragosdydy Do you mean you are trying to use this package directly from React?

If that's the case, then I'd suggest reading about CORS and using [`server.js`](https://github.com/frandiox/medium-json-feed/blob/master/server.js#L7) as a reference to implement your own solution. Either Express server or a Lambda function could work.
